### ISSUE TITLE
feat: close iedit mode if already opened

### ISSUE THREAD

**Issue by mikavilpas** [altermo/iedit.nvim#1]
Hi, thanks for the plugin!

Do you think it would be a good addition to close any active iedit mode if `.select()` is called and the mode is already active?

I would like to drop the extra mapping for `.stop()` and use that instead.

Thanks!

**Comment by altermo** [comment]
[It already does that](https://github.com/altermo/iedit.nvim/blob/main/lua/iedit/init.lua#L58). (Or am I missing something)

[Also added docs to readme clarifying this](https://github.com/altermo/iedit.nvim/commit/233c1a1298987be681c16698a4304b9e22fb8f03).

**Comment by mikavilpas** [comment]
What I'm suggesting is: when a selection is active and a new selection is requested
- close the previous selection with `.stop()`
- do not open a new selection. This is a kind of "toggle off if already on" functionality.

What currently happens (I'm guessing):
- calls `.stop()`
- immediately starts a new selection

What do you think?

**Comment by altermo** [comment]
Okay, added. (https://github.com/altermo/iedit.nvim/commit/80f61d8b325842954781fac4f245feaf44dede7d)

**Comment by mikavilpas** [comment]
Awesome, thanks so much!
