### ISSUE TITLE
Default select all

### ISSUE THREAD

**Issue by viocost** [altermo/iedit.nvim#2]
Hello, thats for great plugin. 

Would it be possible to toggle selecting all by default instead of a first occurrence? 
Maybe a config parameter?

Thank you.
Let me know if you need help.

**Comment by altermo** [comment]
This may already be implemented (though not documented): is `require"iedit".select({all=true})` what you're looking for?

**Comment by viocost** [comment]
Oh right, this one worked for me: `require("iedit").toggle({all=true})`. Thanks again!
